Invisible recording transfers and Core camera coordinate system clarification
pupil-labs/pupil-docs pull request #407
Opened 2021-01-20 11:34 UTC by N-M-T

2021-01-20 12:37 UTC, papr approved these changes
Two small suggestions at the bottom. Remaining documentation reads great!

2021-01-20 12:37 UTC, papr commented on src/invisible/user-guide/invisible-companion-app.md
> +2) Slide down from the top of the device's home-screen and click on 'Android System.USB charging this device'
```suggestion
2) Slide down from the top of the device's home-screen and click on 'Android System - USB charging this device'
```

2021-01-20 12:37 UTC, papr commented on src/invisible/user-guide/invisible-companion-app.md
> +6) Pupil Invisible recordings can be found in the Pupil Invisible folder
```suggestion
6) Pupil Invisible recordings can be found in the Pupil Invisible folder

::: tip
On macOS, you require the <a href="https://www.android.com/filetransfer/" alt="Android File Transfer website">Android File Transfer</a> to browse and transfer files between your Mac computer and your Android device.
:::
```

2021-01-20 13:12 UTC, N-M-T commented on src/invisible/user-guide/invisible-companion-app.md
> +6) Pupil Invisible recordings can be found in the Pupil Invisible folder
Thanks for that mac info!

2021-01-20 13:18 UTC, N-M-T commented on src/invisible/user-guide/invisible-companion-app.md
> +6) Pupil Invisible recordings can be found in the Pupil Invisible folder
Thanks for the mac info!

2021-01-20 13:27 UTC, papr approved these changes

2021-01-21 02:13 UTC, willpatera requested changes
@N-M-T looks good, I have left a few suggestions for you to consider.

2021-01-21 02:13 UTC, willpatera commented on src/invisible/README.md
> +You can also playback and download in [Pupil Cloud](/cloud "Pupil Cloud documentation"),
```suggestion
After uploading to Pupil Cloud, you can playback recordings, enrich data, and download. Check out [Pupil Cloud](https://cloud.pupil-labs.com/ "Pupil Cloud") for more information. 
```

2021-01-21 02:13 UTC, willpatera commented on src/invisible/README.md
> +or [transfer directly](/invisible/user-guide/invisible-companion-app/#recording-transfer) to your
```suggestion

Alternatively you can [directly transfer recordings](/invisible/user-guide/invisible-companion-app/#recording-transfer) to your 
```

2021-01-21 02:13 UTC, willpatera commented on src/invisible/user-guide/invisible-companion-app.md
> +Invisible recordings are uploaded to the cloud from the Invisible Companion App to ensure stability, robustness and security. If you still have the recordings on the Companion device, follow these in
```suggestion
Pupil Invisible recordings can be uploaded cloud storage directly from the Invisible Companion App. We recommend using Pupil Cloud for ease of user experience, stability, robustness, and data security. 

If you made recordings on Pupil Invisible Companion while cloud upload feature was disabled, you can re-enable and upload recordings to Cloud:```

2021-01-21 02:13 UTC, willpatera commented on src/invisible/user-guide/invisible-companion-app.md
> +3) Login to Pupil Cloud to view or download your recording/s!
```suggestion
3) Login to [Pupil Cloud](https://cloud.pupil-labs.com "Pupil Cloud") to playback recordings, enrich data, and download.
```

2021-01-28 09:49 UTC, merged