Section on PI's red LED in Troubleshooting
pupil-labs/pupil-docs pull request #444
Opened 2021-07-16 10:06 UTC by marc-tonsen

2021-07-16 10:46 UTC, papr commented on src/invisible/user-guide/troubleshooting.md
> +The LED is indicating that there is a problem that may affect further data collection and tries to grab your attention. To get details on what the problem exactly is open the Pupil Invisible Companio
```suggestion
The LED is indicating that there is a problem that may affect further data collection and tries to grab your attention. To get details on what the problem exactly is, open the Pupil Invisible Companion app, which will show an error description.
```

2021-07-19 04:40 UTC, willpatera requested changes
@marc-tonsen I made quite a few changes. Please feel free to accept/edit my suggestions.

2021-07-19 04:40 UTC, willpatera commented on src/invisible/user-guide/troubleshooting.md
> +The LED is indicating that there is a problem that may affect further data collection and tries to grab your attention. To get details on the problem, open the Pupil Invisible Companion app, which wi
```suggestion
The LED blinks to try to get the wearer's attention. The red blinking LED indicates that there is a problem that may affect further recording. To get details, open the Pupil Invisible Companion app to view an error description.
```

2021-07-19 04:40 UTC, willpatera commented on src/invisible/user-guide/troubleshooting.md
> +The potential problems incude:
```suggestion
The potential problems include:
```

2021-07-19 04:40 UTC, willpatera commented on src/invisible/user-guide/troubleshooting.md
> +- Low battery on the Companion device.
```suggestion
- Low battery on the Companion Device.
```

2021-07-19 04:40 UTC, willpatera commented on src/invisible/user-guide/troubleshooting.md
> +- Little storage left on the Companion device.
```suggestion
- Low storage space remaining on the Companion Device.
```

2021-07-19 04:40 UTC, willpatera commented on src/invisible/user-guide/troubleshooting.md
> +- Unstable connection to the Pupil Invisible device during a recording.
```suggestion
- Unstable connection to the Pupil Invisible Glasses device during a recording.
```

2021-07-19 08:25 UTC, marc-tonsen commented
Thanks for the edits @willpatera, I accepted all of them. Ready to merge I think!

2021-07-21 04:12 UTC, merged